# Generated by Django 4.0.4 on 2022-05-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='startTime',
            field=models.TimeField(),
        ),
    ]
