int SYSTEM_STATE = 0; 
#define OPENING_SCREEN 0
#define MENU_SCREEN 1
#define START_GAME_SCREEN 2
#define IN_GAME_SCREEN 3
#define GAME_WON_SCREEN 4
#define GAME_LOST_SCREEN 5
#define NAME_UPDATE_SCREEN 6
